### ISSUE TITLE
case create: if "Assigned To" is changed, case can not be created

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#244]
## Description
[ Git: develop - 82077799e98e4a3a75a13d89ef81d4d05508c9d7]

"Create Case" **fails if the assigned_to is changed**. If the default assigned is used, it works

![image](https://user-images.githubusercontent.com/167875/140835622-ab93dcf8-4f0a-4523-bcee-834b3ef97b4d.png)

When a asignee is changed, there is an extra attribute in the payload that cause the error:

#### successful request
![image](https://user-images.githubusercontent.com/167875/140947689-109236cb-9ac1-47a2-afa9-307441a222c2.png)

#### Failed request with extra attribute in payload
![image](https://user-images.githubusercontent.com/167875/140947389-f8b4a75d-d57a-43e0-8a4d-5ae97db20ea1.png)

**Comment by imedina** [comment]
We just need to fix this line:

https://github.com/opencb/jsorolla/blob/develop/src/webcomponents/clinical/clinical-analysis-create.js#L653

**Comment by imedina** [comment]
@pamag this should be fixed now, can you confirm?

**Comment by pamag** [comment]
@imedina  the error still persist.  

Branch develop commit: b7e64ae9643b3d8a5f404e6d456c8599cc410cd5 (2021-11-19)

![image](https://user-images.githubusercontent.com/167875/142558076-a4581385-dbce-4374-99e2-978b91749b69.png)

**Comment by pamag** [comment]
update 2021-12-17
this bug is still active at branch release 2.2.x commit 2310df1b0c050d1381153fd02e23437303fd3164
![image](https://user-images.githubusercontent.com/167875/146686483-d924a3cd-d8c2-49d0-9ade-660bcf884cbf.png)

**Comment by pamag** [comment]
@imedina still is broken in commit c12bf578bb09531f2bed22a594cbcb96b24ae2d3
![image](https://user-images.githubusercontent.com/167875/146812355-b1bf1370-e987-4a12-b098-5f2a211f5fe9.png)

**Comment by pamag** [comment]
## Reviewed

commit f6bea023104151cf7a24ffa94c620aea8fdd23de

Now works OK
