### ISSUE TITLE
Locking a case does not lock interpretations

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#311]
## Describe the bug
Locking a case, locks the form in case manager but not in the tab of case interpretation.

![able_to_edit_interpretation_in_locked_cases](https://user-images.githubusercontent.com/167875/147279288-8ecd2a20-e3e9-48d1-9a60-0b1088aa284b.gif)

Also the buttons for creating or updating interpretations should have a disabled style when the case is locked.
![image](https://user-images.githubusercontent.com/167875/147279600-a125c17b-c1e1-4426-bcd4-87212db5fdd6.png)

**Comment by pamag** [comment]
It also allows to select variants in the sample variant browser
![lock_case_is_not_woking](https://user-images.githubusercontent.com/167875/151141205-8e835e45-b06d-4de3-bdba-2a4494022659.gif)

**Comment by imedina** [comment]
This is now fixed:

![image](https://user-images.githubusercontent.com/1427327/151687407-60df995b-36d5-4d44-a126-5d4a4f0906fb.png)

**Comment by pamag** [comment]
## Reviewed

NOT FULLY FIXED. Still not addressing the ability to add new variants to the blocked interpretation as describe in the comment https://github.com/opencb/jsorolla/issues/311#issuecomment-1022036689

**Comment by imedina** [comment]
@pamag this is now implemented, users cannot select/deselect or edit variants
