### ISSUE TITLE
The samples table in the overview tab of Case Manager need all cell with the same vertical alignment

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#322]
## Improvement 

[UX improvement]

The samples table in the overview tab of Case Manager need all cells with the same vertical alignment

where: Case Interpreter | Case Manager | overview tab

![image](https://user-images.githubusercontent.com/167875/147793111-5fa34c7a-5aa4-44ab-89a7-ef201699b2d2.png)

**Comment by Rodielm** [comment]
Fixed for now https://github.com/opencb/jsorolla/commit/93643976351495268259b2661f0343b8f4bd3712

![image](https://user-images.githubusercontent.com/10471758/147936433-ad2d612e-e9af-4eea-97fb-f416798eab1c.png)

**Comment by pamag** [comment]
## Reviewed

NOT FIXED -> returned to TODO

commit: f104bd4712825f4c4fdc278c088a4b7b7bff1bf0

![image](https://user-images.githubusercontent.com/167875/150710795-0c54f4d0-273a-4e6d-880c-c02bf7b7a1aa.png)

**Comment by Rodielm** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/10471758/151227530-e0799874-d9a7-4d44-a350-bf94d12afe75.png)
